[package]
name = "smithay"
version = "0.1.0"
authors = ["Victor Berger <victor.berger@thalesgroup.com>"]
license = "MIT"

[dependencies]
wayland-server = "0.9.4"
nix = "0.7.0"
xkbcommon = "0.2.1"
tempfile = "2.1.5"
slog = { version = "2.0.0" }
slog-stdlog = "2.0.0-0.2"
libloading = "0.4.0"
wayland-client = { version = "~0.8.6", optional = true }
winit = { version = "~0.6.4", optional = true }
glium = { version = "~0.16.0", optional = true }
input = { version = "~0.1.1", optional = true }
clippy = { version = "*", optional = true }

[build-dependencies]
gl_generator = "0.5"

[dev-dependencies]
slog-term = "~1.5"

[features]
default = ["backend_winit", "backend_libinput", "renderer_glium"]
backend_winit = ["winit", "wayland-server/dlopen", "wayland-client/dlopen"]
renderer_glium = ["glium"]
backend_libinput = ["input"]
