[package]
name = "smithay"
version = "0.1.0"
authors = ["Victor Berger <victor.berger@thalesgroup.com>"]
license = "MIT"

[dependencies]
wayland-server = "0.9.1"
nix = "0.7.0"
xkbcommon = "0.2.1"
tempfile = "2.1.5"
slog = { version = "2.0.0" }
slog-stdlog = "2.0.0-0.2"
glutin = { version = "~0.7.4", optional = true }
glium = { version = "~0.16.0", optional = true }
input = { version = "~0.1.1", optional = true }
clippy = { version = "*", optional = true }

[dev-dependencies]
slog-term = "~1.5"

[features]
default = ["backend_glutin", "backend_libinput", "renderer_glium"]
backend_glutin = ["glutin", "wayland-server/dlopen"]
renderer_glium = ["glium"]
backend_libinput = ["input"]
